### ISSUE TITLE
Group shows up as node when exporting 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#111]
How come when I create a group: 
```
[root@fs2vm111 ~]# lsdef -t group cn_regex
Object name: cn_regex
    grouptype=static
    ip=|cn(\d+)|172.10.(($1-1)/20+1).(($1-1)%20+1)|
    members=
```

It shows up as a node? 

```
[root@fs2vm111 ~]# xcat-inventory export -t group -o cn_regex --format=yaml
Error: Invalid object type: "group"
```

Then when I exported all, i saw it..... under a node object....

```
[root@fs2vm111 ~]# xcat-inventory export -t node -o cn_regex
node:
  cn_regex:
    device_type: server
    network_info:
      primarynic:
        ip: '|cn(\d+)|172.10.(($1-1)/20+1).(($1-1)%20+1)|'
    obj_info:
      grouptype: static
    obj_type: group
    role: compute
schema_version: '1.0'
```

A little confusing....
