### ISSUE TITLE
[FVT]:why we use different attribute names in osimage export stanza file other than in the osimage definition.

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-inventory#145]
I think if we use different attribute names , there is some confusion. Not sure if we use these attributes in other places. if not, could we use the same attribute names?

For example, in following case, we use distribution , osdistro etc, but in osimage definition, we use osvers and osdistroname etc. Could we use these name in consistent.

```
[root@c910f04x12v02 environment]# xcat-inventory export -t osimage -o rhels7.6-x86_64-netboot-compute
osimage:
  rhels7.6-x86_64-netboot-compute:
    basic_attributes:
      arch: x86_64
      distribution: rhels7.6
      osdistro: rhels7.6-x86_64
      osname: Linux
    genimgoptions:
      exlist:
      - /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.exlist
      permission: '755'
      postinstall:
      - /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall
      rootimgdir: /install/netboot/rhels7.6/x86_64/compute
    imagetype: linux
    package_selection:
      otherpkgdir:
      - /install/post/otherpkgs/rhels7.6/x86_64
      pkgdir:
      - /install/rhels7.6/x86_64
      pkglist:
      - /opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.pkglist
    provision_mode: netboot
    role: compute
schema_version: '1.0'
```
osimage definition
```
[root@c910f04x12v02 environment]# lsdef -t osimage -o rhels7.6-x86_64-netboot-compute
Object name: rhels7.6-x86_64-netboot-compute
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels7.6-x86_64
    osname=Linux
    osvers=rhels7.6
    otherpkgdir=/install/post/otherpkgs/rhels7.6/x86_64
    permission=755
    pkgdir=/install/rhels7.6/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.x86_64.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.6/x86_64/compute
[root@c910f04x12v02 environment]#```
