### ISSUE TITLE
An unknown node object is exported on x86_64 arch

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-inventory#168]
on x86_64 arch machine, when I run xcat_inventory export , there is an unknown node object   rh4.1234567890  is exported
```
root@c910f04x12v05:/opt/xcat/share/xcat# xcat-inventory -V
0.1.6 (git commit fe6900cc38a6fa8f2329ad901b14354835561c6e)
root@c910f04x12v05:/opt/xcat/share/xcat# xcat-inventory export -t node
node:
  c910f04x12v06:
    device_info:
      arch: x86_64
      uuid: 5df4278e-fbb7-11e8-95bc-426d0a040c06
    device_type: server
    engines:
      console_engine:
        engine_info:
          serialflow: hard
          serialport: '0'
          serialspeed: '115200'
        engine_type: kvm
      hardware_mgt_engine:
        engine_info:
          vmcpus: '2'
          vmhost: c910f04x12
          vmmemory: '4096'
          vmnicnicmodel: virtio
          vmnics: br10,br4091,br4093
          vmstorage: dir:///var/lib/libvirt/images/
        engine_type: kvm
      netboot_engine:
        engine_type: xnba
    network_info:
      primarynic:
        ip: 10.4.12.6
        mac:
        - 42:6d:0a:04:0c:06
        - 42:78:0a:04:0c:06!*NOIP*
        - 42:6c:0a:04:0c:06!*NOIP*
    obj_info:
      groups: all,vm12
    obj_type: node
    role: compute
  c910f04x12v07:
    device_info:
      arch: x86_64
      uuid: 5b37e210-fbc1-11e8-9f89-42810a040c07
    device_type: server
    engines:
      console_engine:
        engine_info:
          serialflow: hard
          serialport: '0'
          serialspeed: '115200'
        engine_type: kvm
      hardware_mgt_engine:
        engine_info:
          vmcpus: '2'
          vmhost: c910f04x12
          vmmemory: '4096'
          vmnicnicmodel: virtio
          vmnics: br10,br4091,br4093
          vmstorage: dir:///var/lib/libvirt/images/
        engine_type: kvm
      netboot_engine:
        engine_info:
          osimage: ubuntu18.04.1-x86_64-install-compute
        engine_type: xnba
    network_info:
      primarynic:
        ip: 10.4.12.7
        mac:
        - 42:81:0a:04:0c:07
        - 42:a2:0a:04:0c:07!*NOIP*
        - 42:14:0a:04:0c:07!*NOIP*
    obj_info:
      groups: all,vm12
    obj_type: node
    role: compute
    role_info:
      monserver: c910f04x12v05
      nfsserver: c910f04x12v05
      tftpserver: c910f04x12v05
      xcatmaster: c910f04x12v05
  rh4.1234567890:
    device_type: server
    engines:
      hardware_mgt_engine:
        engine_type: hmc
    obj_type: group
    role: compute
  service:
    device_type: server
    engines:
      netboot_engine:
        engine_info:
          postscripts: servicenode
    obj_type: group
    role: compute
  xcatdefaults:
    device_type: server
    engines:
      netboot_engine:
        engine_info:
          postbootscripts: otherpkgs
          postscripts: syslog,remoteshell,syncfiles
    obj_type: group
    role: compute
schema_version: '2.0'

#Version 2.14.5 (git commit fc0fb3fca198aa298a114f6124749275e7d81f8c, built Fri Dec  7 07:18:16 EST 2018)

```
The node list is here
```
root@c910f04x12v05:/opt/xcat/share/xcat# nodels
c910f04x12v06
c910f04x12v07
```
