### ISSUE TITLE
Support list in YAML for user comments

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-inventory#80]
I'm not sure if this will be used, but it am liking the ability to have a single line for a comma separated list.  I tried this for user comment and it did not work. 

Any possibility of supporting user comment  in line by line? 
```
[root@briggs01 xcat_clusters]# cat osimage/rhels/xcat/xcat.redhat-alt.full.install.osimage.yaml
osimage:
  xcat.redhat-alt.full.install:
    basic_attributes:
      arch: ppc64le
      distribution: rhels7.5-alternate
      osdistro: rhels7.5-alternate-ppc64le
      osname: Linux
    deprecated:
      comments:
      - rhels7.5
      - abc
      - ist
      - cuda-9.2.148-1-396.42
    imagetype: linux
```
Results in being wrapped in { } ... 

```
[root@briggs01 xcat_clusters]# xcat-inventory import -f osimage/rhels/xcat/xcat.redhat-alt.full.install.osimage.yaml
Importing object: xcat.redhat-alt.full.install
Inventory import successfully!
[root@briggs01 xcat_clusters]# lsdef -t osimage  xcat.redhat-alt.full.install -i usercomment
Object name: xcat.redhat-alt.full.install
    usercomment={rhels7.5,abc,ist,cuda-9.2.148-1-396.42}
[root@briggs01 xcat_clusters]#
```
