### ISSUE TITLE
Some orphan entries are exported as "groups" and then created as nodegroups when imported.

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-inventory#85]
1. On `boston01` run `xcat-inventory export -t node -f /tmp/gurevich/orphan_groups --format yaml`
    a. Examining the generated file, can see that at least 2 groups that do not exist on `boston01`. Many more groups get written to the file, some exist on `boston01`, some do not exist on `boston01`. I removed all except the two listed below, so this issue can just focus on them.
    ```
     10.6.25.1:
    device_type: server
    network_info:
      primarynic:
        mac:
        - 7c:fe:90:e0:84:2c
    obj_type: group
    role: compute
    ```
    and
    ```
      xcatdefaults:
    device_type: server
    engines:
      netboot_engine:
        engine_info:
          postbootscripts: otherpkgs
          postscripts: syslog,remoteshell,syncfiles
    obj_type: group
    role: compute
    ```
    However:
    ```
    [root@boston01 gurevich]# lsdef -t group xcatdefaults
    Error: [boston01]: Could not find an object named 'xcatdefaults' of type 'group'.

    [root@boston01 gurevich]# lsdef -t group 10.6.25.1
    Error: [boston01]: Could not find an object named '10.6.25.1' of type 'group'.
    ```

    b. If this yaml file gets imported on `boston36`. The two groups get created there:
    ```
    [root@boston36 gurevich]# lsdef -t group xcatdefaults
    Error: [boston36]: Could not find an object named 'xcatdefaults' of type 'group'.

    [root@boston36 gurevich]# lsdef -t group 10.6.25.1
    Error: [boston36]: Could not find an object named '10.6.25.1' of type 'group'.

    [root@boston36 gurevich]# xcat-inventory import -t node -f /tmp/gurevich/orphan_groups
    Importing object: 10.6.25.1
    Importing object: xcatdefaults
    Inventory import successfully!
    [root@boston36 gurevich]#

    [root@boston36 gurevich]# lsdef -t group xcatdefaults
    Object name: xcatdefaults
        members=
        postbootscripts=otherpkgs
        postscripts=syslog,remoteshell,syncfiles

    [root@boston36 gurevich]# lsdef -t group 10.6.25.1
    Object name: 10.6.25.1
        mac=7c:fe:90:e0:84:2c
        members=
    [root@boston36 gurevich]#
    ```

2. This is not a problem with just `boston01`. On `stratton01` running the same `xcat-inventory export` command 
    a. The following groups get written to the yaml file, but they are not visible with `lsdef -t group`: `c910frame5c39:`, `f6u13k20`, `p9euh03`, `testnode1` and some others.
    b. Some groups that are displayed with `lsdef` command, like `lsfvms` are not written to yaml file.
