### ISSUE TITLE
xcat-inventory export passwords only stored one entry per key

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-inventory#86]
1. Run `xcat-inventory export -t passwd -f /tmp/gurevich/pwords --format yaml`
2. Note that 2 entries exist in `passwd` table for `xcat` key
```
[root@stratton01 ~]# tabdump passwd
#key,username,password,cryptmethod,authdomain,comments,disable
"system","root","xxxxx",,,,
"openbmc","root","xxxx",,,,
"ipmi","ADMIN","xxxx",,,,
"omapi","xcat_key","xxxxxx",,,,
"xcat","root","xxxxx",,,,
"xcat","wsuser","xxxx",,,,
[root@stratton01 ~]#
```
3. But the generated yaml file only stores one entry:
```
[root@stratton01 ~]# cat /tmp/gurevich/pwords
passwd:
  ipmi:
    password: xxxxx
    username: ADMIN
  omapi:
    password: xxxx
    username: xcat_key
  openbmc:
    password: xxxxx
    username: root
  system:
    password: xxxxx
    username: root
  xcat:
    password: xxxxxx
    username: wsuser
schema_version: '1.0'

#Version 2.14.3 (git commit d3f1bbbe2642b720222b7927a81984f1d0190eb3, built Fri Jul 13 06:15:47 EDT 2018)
[root@stratton01 ~]#
```

**Comment by immarvin** [comment]
currently, there are some tables with multiple keys:
```
[root@c910f03c05k21 xCAT]# cat ./Schema.pm |grep 'keys =>' -B2|grep -v 'cols =>'

    litefile => {
        keys => [qw(image file)],

--
    passwd => {
        keys => [qw(key username)],
--
    switch => {
        keys => [qw(node switch port)],


```

**Comment by immarvin** [comment]
```
[root@stratton01 ~]# cat /tmp/gurevich/pwords
passwd:
  xcat:
     - root : abcde
     - wsuser : cdefg
  ipmi:
    - ADMIN: xxxx
```

process the scenarios that the `username` or `password` is blank

**Comment by bybai** [comment]
Discussion results:
1. enhance classes in dbfactory and dbobject to support multiple keys objects, like passwd and switch.
Clarify db keys and dict keys.
2. passwd object schema results: combine key and username as the paswd object name, like <key>.<username>, new data format example as following:
```
passwd: 
    omapi.xcat_key: 
        password: xxxxxx 
    xcat.root: 
        cryptmethod: md5 
        password: xxxxx 
    xcat.wsuser: 
        authdomain: test 
        cryptmethod: sha256 
        password: xxxx 
        usercomment: hello 
```
3. schema passwd.yaml is changed as following:
```
!!python/dict
passwd:
    password: "T{passwd.password}"
    cryptmethod:
    - "T{passwd.cryptmethod}"
    - "C:${{option=V{cryptmethod}: True if str(option) in ('','md5','sha256','sha512') else False}}"
    authdomain: "T{passwd.authdomain}"
    usercomment: "T{passwd.comments}"
```
